name             'cerny_workstation'
maintainer       'Nathan Cerny'
maintainer_email 'ncerny@gmail.com'
license          'apache'
description      'Installs/Configures cerny_workstation'
long_description 'Installs/Configures cerny_workstation'
version          '0.1.0'

depends 'apt'
depends 'git'
